keys:
  - &orzklv age17khgylv28qg5we66jxsju2ctqylzvuvvsvxxtgn4afdjz8lzy42slzeq08
  - &shakhzod age1v033llteyfmjwpwv4mf8n9npfpfc9xmttl2g7vcr2wy7qcsaee4qxn3qf9

creation_rules:
  - path_regex: ^secrets/.*\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *orzklv
          - *shakhzod
